services:
  - type: web
    name: parcify
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HUGGING_FACE_API_URL
        sync: false
      - key: HUGGING_FACE_API_TOKEN
        sync: false
    plan: standard
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 